import type { Metadata } from "next"
import { Inter } from "next/font/google"
import NavBar from "./components/NavBar"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Siddharth Rahtod",
  description: "Portfolio Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col gap-6 lg:gap-12`}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
